services:
  primefaces-homeoffice:
    platform: linux/amd64
    build:
      context: .
      platforms:
        - linux/amd64
      args:
        EAP_BUILDER_IMAGE: registry.redhat.io/jboss-eap-8/eap81-openjdk21-builder-openshift-rhel9:latest
        EAP_RUNTIME_IMAGE: registry.redhat.io/jboss-eap-8/eap81-openjdk21-runtime-openshift-rhel9:latest
        EAP_PLATFORM: linux/amd64
    image: primefaces-homeoffice:eap-8.1
    ports:
      - "8080:8080"
